### ISSUE TITLE
Warning output can quickly obscure interactive prompts

### ISSUE THREAD

**Issue by jdemelo** [splunk/qbec#15]
I was following the awesome docs at https://qbec.io/userguide/tour/, and when I got to `qbec apply default`, it seemed like qbec was hanging.

After getting the source and running in a debugger, I saw that the app was sitting on a call to `s, err := inst.Readline()`.

It turns out that the prompt text **was** in fact displayed, but then immediately obscured by many warnings like:

```
[warn] not authorized to list config.istio.io/v1alpha2, Kind=authorization, error ignored
[warn] not authorized to list config.istio.io/v1alpha2, Kind=prometheus, error ignored
```

Knowing this now, I can easily work-around the issue by pressing y or n, even if `Do you want to continue [y/n]` isn't visibile on the screen, or by using `--yes`, but this might be as confusing to other new users as it was to me.

**Comment by gotwarlost** [comment]
ugh. qbec tries to list all objects in the background to calculate the deletion set as the apply is in progress. When this listing has warnings, we get into this weird state where prompts are not visible.

I'll look into sequencing things so that the background list starts after accepting the input.
