### ISSUE TITLE
qbec fail on lists Secrets from k8s cluster

### ISSUE THREAD

**Issue by alexfanat86** [splunk/qbec#256]
When we try to interact with our prod k8s cluster, we've got the error:
```
[kube-admin]$ qbec diff -c rbac prod -v8 -k Secrets
...
cluster metadata load took 136ms
1 components evaluated in 34ms
[warn] 0 of 94 matches for kind filter, check for typos and abbreviations
13 components evaluated in 167ms
not listing objects of type /v1, Kind=Endpoints
using cluster scoped queries for multiple namespaces
waiting for deletion list to be returned
list objects: type=/v1, Kind=Secret,namespace="" took 4.148s
---
stats: {}

✘ list errors:list /v1, Kind=Secret : rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (2172669916 vs. 2147483647)
command took 4.57s
```

Our environment:
K8s version v1.19.8

If try to get Secrets with qbec labels via kubectl it works fine:
```
[kube-admin]$ kubectl get secrets -A -l 'qbec.io/application=ozon,qbec.io/environment=prod,!qbec.io/tag'
NAMESPACE              NAME                              TYPE     DATA   AGE
kubernetes-dashboard   kubernetes-dashboard-csrf         Opaque   1      545d
kubernetes-dashboard   kubernetes-dashboard-key-holder   Opaque   2      545d
```

All secrets in cluster:
```
[kube-admin]$ kubectl get secrets --context o-prod -A --no-headers | wc -l
   24241
```

If you need more information just ask

**Comment by gotwarlost** [comment]
The bug is pretty simple to understand (I haven't looked at fixes yet)

* qbec lists everything not just the objects matching labels because a thing that exists without the labels should show up in the diff as a mod rather than an add, and to handle other edge cases
* it currently doesn't using the pagination feature offered by the k8s list API. Ideally we would limit each list result to 1000 objects or something and build the full list in memory that way.

I'm on vacation for the next 3 days and will take a look Sunday/ Monday

**Comment by gotwarlost** [comment]
ok the above description is not quite true. qbec does use label selectors for the list
