### ISSUE TITLE
Duplicate objects when generating multiple objects of same kind with `generateName`

### ISSUE THREAD

**Issue by davidreuss** [splunk/qbec#29]
Hello,

I see the duplication check was recently added which is a really nice feature. Would it make sense to keep it behind a flag, seeing as it breaks existing configs, relying on this "feature" not being present?

Should the case be supported where you have multiple objects of the same type with `generateName` being set?

For instance, you might have a component which emits a list of pods, which you want to apply always, and get new pods.

Currently that's not possible due to the duplication check coming in effect.

Example component:

```
{
  pod1: {
    apiVersion: 'v1',
    kind: 'Pod',
    metadata: {
      generateName: 'pod1-',
    },
    spec: {},
  },
  pod2: {
    apiVersion: 'v1',
    kind: 'Pod',
    metadata: {
      generateName: 'pod2-',
    },
    spec: {},
  },
}
```

Thanks for `qbec` .. currently evaluating it for replacing our own internal tool which maps nicely to the feature set, which was also inspired greatly by `ksonnet`, without the craziness 😂

**Comment by gotwarlost** [comment]
First of all, thank you for evaluating qbec. It's good to see people from outside the neck of our woods getting interested in this project.

I never imagined qbec being used to create ephemeral objects. To be honest, I didn't think that this would have worked even with qbec 0.6.x but apparently it does :) 

I would like to understand this use-case better. For instance, one of the big features of qbec IMO is automatic garbage collection and that is not possible for this use-case.

I don't want to hide the dup check behind a feature flag because I think it should be turned on by default so that people don't accidentally shoot themselves in the foot by creating duplicate deployments etc. I would prefer to handle the `generateName` case as a first-class citizen and do the right things when people have specified this. 

I definitely want this tool to get wider adoption so I'm happy to work with you to make this happen. Let's discuss on how this should work and I will make the code changes to reflect the discussion. In the meantime please continue evaluating qbec with the 0.6.x version. Thanks!

**Comment by gotwarlost** [comment]
Note to self: generateName is a really good way to create `job` objects, i.e. one-shot things that don't stick around and never need to be garbage collected. In fact, job objects cause problems in qbec right now because qbec tries to update them in-place and mostly fails since most attributes in that object cannot be updated. 

So, if we were to support `generateName` as a first-class thing:

* no impact to show or validate
* diff should always show the object as being created (perhaps with a YAML comment explaining why)
* apply shouldn't bother to lookup an object with a blank name and simply create
* dup checks should ignore such objects
* GC should ignore objects with `generateName` 

seems easy if I've gotten the above right.

**Comment by gotwarlost** [comment]
@davidreuss - I can't get objects with `generateName` to work in qbec 0.6.x. It complains that the remote object was a blank name was not found. Did this ever work for you or was your bug report speculative?

**Comment by davidreuss** [comment]
we haven’t gotten to a place where we use qbec’s apply — we’re merely using it for generating the components and use our own applier on top of that .. we’d like to down the road use qbec fully.

Regarding jobs and generateName — sounds like you got the idea/requirements just about right .. in our case we use it mainly for applying argo workflows — but also a few bootstrap pods .. (so resulting in new objects always)

this is in CI/e2e context, so it’s mostly one offs rebuilding a full “environment” — so it has not been a requirement to be able to “update” it, but we’re moving it in a direction such that it would.

Thanks for looking into this.

**Comment by gotwarlost** [comment]
so I took a look at how to support this. Doing show, diff, apply, validate etc. are all trivial.

What's more interesting is how garbage collection should behave on apply when generated objects are in play. 

Some options:

* do nothing. If object matches qbec's label expressions but has generateName set, qbec will back off and never try to delete it.

In this case `qbec delete` will leave objects with generated names untouched.

* always delete. Delete all objects matching qbec's label expressions that are not found locally with the caveat that if the object has a generateName set, it will only be deleted provided it is older than when the current apply run started. This will have the effect of creating new objects with generated names but delete older objects without affecting the objects in the current run.

In this case `qbec delete` will always delete all objects.

* allow setting this behavior to either of the above via a `qbec.yaml` attribute, globally. 

* allow setting this behavior *per object type* as a `qbec.yaml` attribute object

* allow user to control this per-object by setting a `hints.qbec.io/gc` annotation.

* some combination of the above.

/cc @splkfinn @bbourbie  your thoughts?

**Comment by davidreuss** [comment]
I don’t have any input as to how delete would be expected/supposed to work, but having the control per object would be valuable - maybe combined with a flag/setting for opt-in of “global” behaviour per run/invocation.

**Comment by gotwarlost** [comment]
Consensus from people I've talked to is a hard-coded default behavior that can be customized with a single `qbec.yaml` attribute for all `generateName` objects and per-object overrides using annotations. I'll proceed with this approach in mind.

**Comment by gotwarlost** [comment]
@davidreuss v0.7.1 has the changes to support `generateName` objects. Give it a whirl and let me know if this fixes your issues.
